### ISSUE TITLE
[Bug] This react component can't import deepspeech npm

### ISSUE THREAD

**Issue by hojihun5516** [Bogglian/react-DeepSpeech#8]
**Describe the bug**
when react component import node including 'deepspeech' It makes error 

**To Reproduce**
1. Go to repository path
2. yarn start

**Expected behavior**
If you click 'submit' button then deepspeech will be run 

**We will try**
1. only deepspeech packaging

**Comment by rayleighko** [comment]
can you try use `electron`? However, this method can incur learning costs.

If you want to solve the problem in a way other than this, you'll need to run your own API using `AWS lambda` or use `nodejs`.

**Comment by hojihun5516** [comment]
Ok I will try using electron

**Comment by rayleighko** [comment]
Now this issue is closed. I'd like you to register another issue with Electron.
